//Categories
export const SEND_CATEGORIES = 'SEND_CATEGORIES';
export const SEND_CURRENT_CATEGORY = 'SEND_CURRENT_CATEGORY';

//Posts
export const SEND_ALL_POSTS = 'SEND_ALL_POSTS';
export const SET_CURRENT_POST = 'SET_CURRENT_POST';
export const SEND_UPDATED_POST = 'SEND_UPDATED_POST';
export const SEND_POST_FILTER = 'SEND_POST_FILTER';
export const ON_SEND_NEW_POST = 'ON_SEND_NEW_POST';
export const DELETE_POST = 'DELETE_POST';

//Comments

export const SEND_COMMENT_LIST = 'SEND_COMMENT_LIST';
export const SEND_UPDATED_COMMENT = 'SEND_UPDATED_COMMENT';
export const SET_COMMENT_TO_EDIT = 'SET_COMMET_TO_EDIT';
export const ON_NEW_COMMENT_AUTHOR_CHANGE = 'ON_NEW_COMMENT_AUTHOR_CHANGE';
export const ON_NEW_COMMENT_MESSAGE_CHANGE = 'ON_NEW_COMMENT_MESSAGE_CHANGE';
export const ON_CREATE_NEW_COMMENT = 'ON_CREATE_NEW_COMMENT';
export const ON_DELETE_COMMENT = 'ON_DELETE_COMMENT';